
version: '3.8'

services:
    api_gateway:
        container_name: api_gateway
        image: api-gateway:ft_transcendence
        build:
            context: .
            dockerfile: api-gateway/Dockerfile
        ports:
            - "80:80"
            - "8080:8080"

        restart: always

        # to remove later:
        volumes:
            - "/Volumes/EL\ MOUDDEN/Project/ft_transcendence/srcs/frontend/:/usr/share/nginx/html"

    auth_service:
        container_name: auth_service
        image: auth-service:ft_transcendence
        build: authentication
        env_file:
            - ./secrets/.auth_service.env

        restart: always

        # to remove later:
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
          - "/Volumes/EL\ MOUDDEN/Project/ft_transcendence/srcs/authentication/app:/app"
