# Generated by Django 4.2.16 on 2024-12-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='blocked_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
